app.directive("cssApplicator", function(StylingFactory){
  return {
    restrict: "E",
    templateUrl: "/js/common/directives/applyCssStyling/applyCssStyling.template.html",
    link: function(scope, element, attrs){
      scope.newClass.styles = [{ key: "", value: ""}];

      // Resets form and style group.
      var resetScopeStyleObjs = function(){
        scope.newClass.name = "";
        scope.newClass.styles = [{key: "", value: ""}];
        scope.styleGroup = {};
        // return;
      }

      // Checks if className assigned. If not, assigns autogenerated name.
      var assignClassName = function(nameVariable){
        if(!nameVariable) return StylingFactory.autoGenName();
        return nameVariable;
      }

      /*  Executes two styling factory methods, the first, to populate the page stylesheet object (held in StylingFactory) and the second, to apply the styling (inline) to the group selected. */
      var applyStylingAndClass = function(nameOfClass, stylingObj, styleGroup){
        StylingFactory.populateStyleSheetObject({name: nameOfClass, cssObj: stylingObj})
        StylingFactory.applyStylingToGroup(styleGroup, stylingObj, nameOfClass, resetScopeStyleObjs);
        return;
      }

      // Adds a new empty field to this directive template for a new style.

      scope.addNewCssField = function(){
        scope.newClass.styles.push({ key: "", value: ""});
        return;
      }

      /* Removes a style field from this directive (will work on empty string keys too.) May also be extended to allow removal from an existing class*/

      scope.removeStyle = function(style){
          var toRemoveIdx = scope.newClass.styles.indexOf(style.key);
          scope.newClass.styles.splice(toRemoveIdx, 1);
          return;
      }

      /* Iterates over each style field in directive and creates new obj with keys as css properties, and values as values */
      scope.getCssFormData = function(data){
        var cssToApply = {};

        data.styles.forEach(function(cssObj){
          cssToApply[cssObj.key] = cssObj.value;
        })

        var newClassName = assignClassName(scope.newClass.name);

        applyStylingAndClass(newClassName, cssToApply, scope.styleGroup);
        scope.pageStyleSheet = StylingFactory.getStyleSheetClassNames();
        return;
      },

      scope.updateClass = function(stylingObj){
        scope.classEditMode = false;
      }
    }
  }
})
